apiVersion: v1
kind: Pod
metadata:
  labels:
    run: yq-nginx
  name: yq-nginx
  namespace: user-25
  uid: 0fecbc66-c3dc-4656-a358-a7fa2be0b3c3
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: yq-nginx
    volumeMounts:
    - name: htmldir
      mountPath: /usr/share/nginx/html
      readOnly: true
    env:
      - name: DUMMY_DATABASE_PASSWORD
        value: admin
    resources: 
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    startupProbe:
      httpGet:
        port: 80
        path: /
        scheme: HTTP
        httpHeaders:
          - name: Custom-Header
            value: Orz
    livenessProbe:
      httpGet:
        port: 80
        path: /
        scheme: HTTP
        httpHeaders:
          - name: Custom-Header
            value: Orz
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3 
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-cqm74
      readOnly: true
  - image: busybox
    name: busybox
    env:
    - name: DUMMY_DATABASE_PASSWORD
      value: "admin"
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $DUMMY_DATABASE_PASSWORD >> /html/index.html; sleep 10;done"]
    volumeMounts:
    - name: htmldir
      mountPath: /html
      readOnly: true
    resources: 
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "100m"
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-esun-lecture-1-pool-4-4303c2db-jl39
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: htmldir
    emptyDir: {}
