# pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: user-35
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
# secret
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credential
  namespace: user-35
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: mysql
---
# pod
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: user-35
  labels:
    app: mysql
spec:
  containers:
  - name: db
    image: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-credential
          key: MYSQL_ROOT_PASSWORD
    volumeMounts:
    - name: mysql-persistent-storage
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-persistent-storage
    persistentVolumeClaim:
      claimName: mysql-pv-claim
# svc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql-svc
  namespace: user-35
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP