# pod
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: wordpress
  name: wordpress
  namespace: user-35
spec:
  containers:
  - image: wordpress
    imagePullPolicy: Always
    name: wordpress
    env:
    - name: WORDPRESS_DB_HOST
      value: mysql-svc
    - name: WORDPRESS_DB_USER
      value: root
    - name: WORDPRESS_DB_PASSWORD
      value: mysql
---
# nodeport
apiVersion: v1
kind: Service
metadata:
  labels:
    run: wordpress
  name: wordpress-np-svc
  namespace: user-35
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30300
  selector:
    run: wordpress
  type: NodePort