apiVersion: v1
kind: Service
metadata:
  labels:
    run: wordpress
  name: wordpress-np-svc
  namespace: user-35
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 80
    nodePort: 30300
  selector:
    run: wordpress
  type: NodePort
